<a href="https://colab.research.google.com/github/Vasan-th/Stats/blob/main/Markov_chains_and_Monte_Carlo_simulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **MARKOV PROCESS**


Next state from a set of possible states depends on the current state and not by any previous state

In [1]:
import numpy as np

In [5]:
# states
state = {0: 'Burger', 1: 'Pizza', 2: 'Hotdog'}

In [6]:
# transition matrix
t = np.array([[0.2, 0.6, 0.2], [0.3, 0.0, 0.7], [0.5, 0.0, 0.5]])
t

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

**Random Walk on Markov chain**

In [10]:
# no. of iterations
n = 15
start_state = 0
prev_state = start_state
print(state[prev_state], end = '') # in python after print it automatically inserts a new line character in order to negate it we are using end
while n:
  # calculating the next state based on the transition probability from prev state
  curr_state = np.random.choice([0, 1, 2], p = t[prev_state])
  print('-->', state[curr_state], end = '')
  prev_state = curr_state
  n -= 1
print('-->done')


Burger--> Pizza--> Hotdog--> Hotdog--> Hotdog--> Hotdog--> Burger--> Pizza--> Hotdog--> Burger--> Pizza--> Hotdog--> Burger--> Pizza--> Burger--> Hotdog-->done


## **Calculating the stationary/equilibrium probabilities**

**Approach I: Monte Carlo simulations**

We will run the random walk for a longer time period (iterations) and calculate the probabilities of each state, which gives us the stationary probabilities for each state

In [18]:
steps = 10**6
start_state = 0
curr_state = start_state
pi = np.array([0, 0, 0])
pi[start_state] = 1

i = 0
while i<steps:
    curr_state = np.random.choice([0,1,2], p=t[curr_state])
    pi[curr_state]+=1
    i +=1

print("Stationary probabilities = ", pi/steps)

Stationary probabilities =  [0.352079 0.211124 0.436798]


**Approach II: Repeated Matrix Multiplication**

If the transition matrix is sufficiently multiplied with itself, then all the rows of the final matrix will represent the stationary probabilities

In [20]:
t1 = t
for i in range(10**3):
  t1 = np.matmul(t1, t)

print('Transition matrix after 10^3 repeated multiplication:', t1)
print('Stationary probabilities: ', t1[0][:])

Transition matrix after 10^3 repeated multiplication: [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]]
Stationary probabilities:  [0.35211268 0.21126761 0.43661972]


**Approach III: Finding left eigen vectors with 1 as its eigen values**

In [22]:
from scipy import linalg
eigen_values, left_eigenvectors = linalg.eig(t, right = False, left = True)

print('Eigen_values:',eigen_values)
print('Left eigen vectors:', left_eigenvectors) # each column in this matrix corresponds to an eigen vector whose eigen value is given by corresponding index values in eigen_values



Eigen_values: [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]
Left eigen vectors: [[-0.58746336+0.j          0.16984156+0.35355339j  0.16984156-0.35355339j]
 [-0.35247801+0.j         -0.67936622+0.j         -0.67936622-0.j        ]
 [-0.72845456+0.j          0.50952467-0.35355339j  0.50952467+0.35355339j]]


In [27]:
pi = left_eigenvectors[:,0]
pi_normalized = [(x/np.sum(pi)).real for x in pi]
pi_normalized

[0.3521126760563379, 0.21126760563380304, 0.4366197183098591]